### ISSUE TITLE
Python to java

### ISSUE THREAD

**Issue by Tharbad** [pybee/voc#129]
Hi,

I'm just trying to help. In a recent search for a friend I've found the following projects:
1) https://github.com/chrishumphreys/p2j - Code converter. Old but worked at some point.
2) https://www.py4j.org/index.html - Allows python code to access jvm objects
3) https://github.com/LeeKamentsky/python-javabridge/ - Same as 2.
4) https://github.com/originell/jpype - Allows python to call java code. You might want to use it.
 
Hope some of them will help you

**Comment by freakboy3742** [comment]
Thanks for those links - however, you may want to [read our FAQ](http://voc.readthedocs.io/en/latest/intro/faq.html), because those projects are taking a completely different approach to what VOC is doing. 

VOC isn't a code converter - it operates at the bytecode level. It compiles Python bytecode *directly* to a Java class file. There is no intermediate "Java source code" version of the project. Python objects become indistinguishable from Java objects, because once compiled by VOC, they *are* Java objects. 

Since all the Python objects are Java objects, you get automatic access to the entire JVM object space and libraries, without any need for bridging or the need to run 2 virtual machines. Your Python code runs completely natively on the JVM.
