### ISSUE TITLE
Use a single Java session for tests

### ISSUE THREAD

**Issue by freakboy3742** [pybee/voc#13]
The current test runner validates Java output by starting a fresh VM for every test. However, JVM warmup is time-expensive operation. 

Ideally, we'd be able to use a single JVM instance, and run each test in that instance, rather than restarting the JVM each time. 

If necessary, this could be done on a per-TestCase or per test Module level.

**Comment by cflee** [comment]
I tried tweaking the TieredCompilation and TieredStopAtLevel options on the [Java HotSpot VM](http://docs.oracle.com/javase/8/docs/technotes/guides/vm/performance-enhancements-7.html) but a rough test showed it was at best equal, and usually worse than without those options.

I was also looking at [Drip](https://github.com/ninjudd/drip) as well, which looks very interesting, but I'm not sure if it's feasible to keep a sufficiently large pool of JVMs running such that we can use and dispose of one every 0.x seconds without ever having to wait for the pool to replenish.

On the other hand, after a bunch more work, I do have a very, very rough proof of concept working using [nailgun](https://github.com/martylamb/nailgun). Nailgun works by keeping a JVM running a server that listens to a socket for commands, and accompanying C client that issues commands to run a particular class. However, it doesn't seem to be able to run the transpiled classes directly, maybe because the classes in tests/temp/* don't exist when Nailgun is started, or because it keeps being replaced.

(There is a python port of the client, but I haven't tried that yet.)

 [Classpath-manager](https://github.com/stuartsierra/classpath-manager) tries to address this by having a class that reads a list of configurable classpaths, creates a new URLClassLoader and loads them, then spawns a new Thread, attaches the ClassLoader to it, then invokes the main() method of the desired class within the Thread. In other words, this acts as a layer of indirection so that the ever-changing freshly transpiled classes in tests/temp/* can get freshly loaded for each test. I did have to monkey-patch it to avoid using the smart ClassLoaderCache, as reusing the ClassLoader doesn't work.

The good news:

```
python3 setup.py test -s tests.datatypes.test_int.UnaryIntOperationTests
unchanged: 7.62s
nailgun: 1.761

python3 setup.py test -s tests.datatypes.test_int
unchanged: 723.179s
nailgun: 94.342s

python3 setup.py test
unchanged: <no result, never ran this on my machine>
nailgun: 610.148s
```

The bad news: 

1. [Lots and lots of failures](https://gist.github.com/cflee/3a8e93ea8683ae6bb81f), even after I do a quick patch of the JAVA_EXCEPTION regex. Some of these, like test_argv, are failing due to the different runtime environment, but the causes of many others aren't immediately obvious (to me).
2. Nailgun seems unmaintained, and both [issues](https://github.com/martylamb/nailgun/issues) and [pull requests](https://github.com/martylamb/nailgun/pulls) may be going unaddressed.
3. No official binaries for nailgun available, apart from [homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nailgun.rb). I haven't tried building nailgun; classpath-manager doesn't build successfully due to some maven issue, but that's still quite doable with a short shell script.

Moving forward, I guess we need to figure out why the tests fail, of course.

Distributing/referencing Nailgun seems tricky too: using the Python client instead of C client should help with this, but I'm not sure what's the best way to integrate that into this repository. That probably needs to be dealt with before the test suite can be wired up to start/stop the nailgun server, etc.

**Comment by freakboy3742** [comment]
Very interesting results - I certainly wouldn't complain about an order of magnitude speedup!

The test failures you're seeing definitely look interesting - from a quick inspection, it looks like something odd is happening to the class hierarchy, because some classes are being identified as "native module" when they should just be "class". That suggests to me that something is happening to the classes on import that is causing them to be misidentified. If it helps, the code that does the identification is all in `org.python.types.Type.pythonType()`.

If there's an existing turnkey solution for this, then we should absolutely use it - however, it hadn't occurred to me to look to the class loader for the solution here. Essentially, all we need here is a Java program that starts the VM, displays a text prompt, and when you type the name of a java class, uses a custom, non-caching class loader to load the named class, runs the main method, and flushes the class cache afterwards. There's no need to be multi-threaded, or controlled by a socket through a C client - a simple single threaded process is fine - as long as it only has one VM instance.

**Comment by cflee** [comment]
I'm still working on getting the classloader to reliably reload/unload the classes without spawning a new thread, but there's something interesting I observed about the transpiled classes - they don't seem to be runnable twice. Is it also an issue that needs to be fixed on the Java end, or is it expected?

```
00:14:27 ~/Desktop/voc-dev $ java -cp voc/dist/python-java.jar:. CLTest
Enter class name > Test
Hello world! Wed Mar 16 00:14:31 SGT 2016
Enter class name > python.test.__init__
8
Enter class name > Test
Hello world! Wed Mar 16 00:14:36 SGT 2016
Enter class name > python.test.__init__
Enter class name > 
```

Test is the standard println-hello-world Java class. I observed this earlier with nailgun but thought it was just nailgun being weird.

**Comment by cflee** [comment]
Oops, that's actually just the default classloader finding the `python.test.__init__` class before the custom classloader gets to have a go! You're absolutely right, it works with embarrassingly few lines of code.

Now to figure out how to link this into utils.py.

**Comment by cflee** [comment]
Okay, so now there is a small program that instantiates a ClassLoader to load a class from the tests/temp/ directory, and invoke its main() method, based on the class name supplied from stdin.

Compared against the earlier figures:

```
python3 setup.py test -s tests.datatypes.test_int.UnaryIntOperationTests
unchanged: 7.62s
nailgun: 1.761s
testdaemon: 2.134s

python3 setup.py test -s tests.datatypes.test_int
unchanged: 723.179s
nailgun: 94.342s
testdaemon: 107.140s

python3 setup.py test
unchanged: <no result, never ran this on my machine>
nailgun: 610.148s
testdaemon: 527.412s
```

It's still 68 failures, probably the same tests. I did have to skip the `tests.stdlib.test_sys.test_exit` as it was causing the test runner to hang, haven't looked into if it was actually exiting or anything like that.

Here is the [Travis build](https://travis-ci.org/cflee/voc/builds/116321927) which ran in 9 min 37 sec. (I've finally figured out that I can enable Travis CI on my own fork, so I can test it there without creating a pull request! This, and the `python setup.py test -s [testcase]` chunk in the docs might be good additions to the first contributions wiki article.)

1 - Is there a better place to hook in so that we reuse it once per test run? Or is it safe to just start without tearing it down? This is relatively negligible though, since there aren't _that_ many test classes so far.

```
python3 setup.py test -s tests.datatypes.test_int
testdaemon (start jvm per class): 107.140s
testdaemon (start jvm globally): 104.359s
```

2 - Is there some alternative to creating and deleting the tests/temp/ directory for every single test run? It seems like it has some small impact on the test duration as well. If it's not absolutely necessary, maybe the `shutil.rmtree(test_dir)` can occur after the end of the entire test run.

```
python3 setup.py test -s tests.datatypes.test_int
testdaemon (creating and deleting temp): 107.140s
testdaemon (not touching temp): 101.968s
```

**Comment by freakboy3742** [comment]
Awesome - great work. 

I've taken a look at the test failures - it looks like it might be a problem loading related classes. Most of the simple tests only need a single main test class; however, the more complex tests generate more than one class, and they all need to be present for the test to run. Many of the test failures you're seeing would be consistent with not being able to find those support classes - either because they're not being compiled, or they're not being loaded successfully, or they're being flushed from the class loader cache too soon, or they're being loaded by a different class loader and not being replaced correctly when a new test class starts.

Regarding your two questions:

1) The easiest option I can think of is to use class level or module level fixtures:

https://docs.python.org/3.4/library/unittest.html#class-and-module-fixtures

It would also be possible to write a custom test runner that has a "whole test run" setUp and tearDown. This would mean some tweaks to how the test suite is invoked, but it shouldn't be too hard to manage.

2) It hadn't occurred to me that creating the test directory would be a performance issue. There's no fundamental reason the directory needs to be created and destroyed on every test; the directly obviously needs to exist, and you need to make sure that there's nothing stray in there that might get picked up as a class file that shouldn't exist in a particular test - but other than that, there's no reason I can think of that the "whole test run" setUp and tearDown couldn't take control of the process of creating and destroying the temp directory.

**Comment by cflee** [comment]
It seems that `Type.pythonType()` needs to have access to the runtime/transpiled classes as well, but it wasn't able to find them. This is because the `org.python.types.Type` class was loaded by the default app classloader from `java -classpath`, but the other classes are loaded by the separate classloader.

Loading the jar at runtime for each test works, but it's is too slow. Keeping another URLClassLoader around just for the jar, chained as the parent classloader, goes back to the original problem - the classes in the jar can't see the runtime classes. Doing a [CompositeClassLoader](https://github.com/stuartsierra/classpath-manager/blob/master/src/main/java/com/stuartsierra/cm/CompositeClassLoader.java) to sequentially try the two classloaders fails.

Finally, I found an '[JoinClassLoader](http://www.source-code.biz/snippets/java/12.htm)' implementation that queries all the delegated classloaders at a lower level (using `ClassLoader.getResource()` instead of `ClassLoader.loadClass()`). This works, and [cuts down the failures to 18](https://travis-ci.org/cflee/voc/builds/116597398), but the duration required goes back up to 35 min. This is likely because the classes from the python-java.jar are being repeatedly loaded, so only the actual JVM overhead is eliminated, while the python-java.jar overhead is still there.

Implementing a static synchronized Map to cache classes from python-java.jar brings the [runtime back down to 10-11 min on Travis, but with more (33) errors](https://travis-ci.org/cflee/voc/builds/116618297). :disappointed: 

Is the [JoinClassLoader](http://www.source-code.biz/snippets/java/12.htm)'s LGPL compatible with this project's BSD license? I could remove it and re-derive it from the ClassLoader abstract class but it would take a little while.

(Also, for some reason, the Python part of the tests running on Travis produce `TypeError: tuple indices must be integers, not float` while they produce `TypeError: tuple indices must be integers or slices, not float` on my machine.)

**Comment by cflee** [comment]
Okay, it's down to [2 failures](https://travis-ci.org/cflee/voc/builds/116945024), running in 10-11 min on Travis. Part of it was getting ImportLib to use the "current" classloader instead of the previous-test-run one, and clearing the static cache of classes that ImportLib was holding onto. Those two items were causing very strange errors where tests only worked the first time, if their underlying classes were updated later.

Also, as I was only working on `runAsJava` earlier, I did not include the `tests/java/` output folder that `assertJavaExecution` uses - that solved another stack of issues where `org.python.java.Module` was present instead of `org.python.types.Module`, and thus failing to be cast to `org.python.Callable`.

The final `test_argv` test seems a bit tricky. It's parsing `System.getProperty("sun.java.command")` which is correctly picking up the testdaemon JVM's command line args, instead of what is passed to `main()`. I'm not sure if there is a reliable proxy for that.

The other test, which fails locally but not on Travis, is `test_implement_interface`. I'm still looking into this.

**Comment by cflee** [comment]
I think there are two ways to deal with the argv issue. We can fallback to the individual JVM invocation when there are args passed in. Otherwise, we can find a way to get the value from the main method's `String[] args` instead of `System.getProperty("sun.java.command")`, but that seems decidedly non-trivial. I guess it depends on how often the tests will have command line args.
