### ISSUE TITLE
Asyncio & common patterns like `with` is missing

### ISSUE THREAD

**Issue by sideffect0** [pybee/voc#245]
`with` and `async/await` is missing

 `raise NotImplementedError('No handler for With')`

**Comment by sideffect0** [comment]
@freakboy3742 need an http client also

**Comment by eliasdorneles** [comment]
Btw, `with` support (which is very popular and exists in Python since 2.5) should probably be a separate issue than `async/await` (which is 3.5+ only)

**Comment by sideffect0** [comment]
@eliasdorneles thats what am saying :(

**Comment by eliasdorneles** [comment]
Erm, no, I just meant to say that it should be two separate tickets instead of just one.
I haven't even used async/away in any production project, so I'd say it doesn't have the same priority as `with` statement.

And we shouldn't complain about lack of features, remember this is a result of a labor of love and volunteering. Let's not forget this is a lot of work and we're getting all of it for free. :heart:

**Comment by sideffect0** [comment]
@eliasdorneles `with` support is a need one :(, am changing the description
