### ISSUE TITLE
Fix incorrect handling of __main__

### ISSUE THREAD

**Issue by cflee** [pybee/voc#346]
Given this Python code:

```python
print('A')

if __name__ == '__main__':
    print('B')

print('C')
```

CPython prints ABC, while VOC prints ACB. This causes at least two tests to fail. [1]

This arises from how VOC is transforming the Python `if __name__ == "__main__":` statement. B is placed into the Java `main()` method, while A and C are placed into `module$import()`. 

At runtime, the JVM starts with the `main()` method, which first invokes `module$import()`, then proceeds to B. This is incorrect behaviour.

One possible fix is to move the children of `if __name__ == "__main__":` into something like `module$main()`, and change `main()` to invoke `module$import()` with a flag main=true. The latter then contains a conditional that invokes `module$main()` at the spot where `is_mainline_def()` is found.

[1] `tests.structures.test_function.FunctionTests.test_mainline` and `tests.stdlib.test_sys.SysModuleTests.test_exit`

**Comment by freakboy3742** [comment]
Confirming that this happens, and that it was mildly intentional, even though it's inconsistent with CPython behaviour.

Java has a specific concept of a "mainline", which Python doesn't; the conceit of a `__name__ == "__main__"` if block being converted into a Java `main()` method seemed a reasonable one, given that the overwhelming pattern of usage is to have that if block as the thing in an entry point.

In the early days of VOC, this was necessary because the `__name__` symbol couldn't be set to `__main__` until after the static block for a class was invoked. However, the recent change to use an `module$init()` method means we have control over the invocation order, so we might be able to fix this - remove the special handling of the "main if", and just have the module level `$init` invoked with __name__ set correctly. Any patch that verifies that this works would be welcome.

This might also open up some options for better handling of modules with `__main__` modules. I haven't worked this through completely, but if a __main__ module exists, it might be possible to invoke *that* module if you try to start the parent module.
