### ISSUE TITLE
Link for getting started guide in README.rst is broken

### ISSUE THREAD

**Issue by ashwani99** [pybee/voc#366]
In README.rst file the link for [Getting Started guide](https://voc.readthedocs.io/en/latest/intro/getting-started.html) is broken. This should be replaced with this [link](https://voc.readthedocs.io/en/latest/intro/index.html)

**Comment by deep110** [comment]
yes, I have pointed it out to @eliasdorneles, he told he will fix it soon.

**Comment by ashwani99** [comment]
Can I fix the link and submit a PR?

**Comment by eliasdorneles** [comment]
I think the best solution is to add redirects, because there are other places pointing to these links.

I don't have the proper permissions to [add page redirects in ReadTheDocs for VOC](http://docs.readthedocs.io/en/latest/user-defined-redirects.html#page-redirects) -- maybe @glasnt @freakboy3742 can have a look?

We'll need it like:

```
Type: Page Redirect
From URL: /intro/getting-started.html
To URL: /intro/index.html
```

**Comment by freakboy3742** [comment]
Redirects would be overkill here; yes, we need to update the links on most BeeWare project READMEs, but just updating the link should be enough.

**Comment by eliasdorneles** [comment]
Well, there are links in the Wiki also: https://github.com/pybee/voc/wiki/Your-first-VOC-contribution
