### ISSUE TITLE
GSoC: Complete implementation of Set and FrozenSet and partial implementation of socket module

### ISSUE THREAD

**Issue by bitdumper1** [pybee/voc#477]
Task
====
I will complete the implementation of the `Set` and `FrozenSet` data types and partially implement the `socket` module.

Goal
====
100% completion of `Set` and `FrozenSet` and 75% (40) methods from the [socket](https://docs.python.org/3/library/socket.html) module.

Technical details
=============
`Set` and `FrozenSet`
----------------------------
`Set` and `FrozenSet` are same and both can be done at the same time.

The following methods will be implemented in `Set` and `FrozenSet` which are simple.
* `sub`, `rsub` and `isub`
* `and`, `rand` and `iand`
* `xor`, `rxor` and `ixor`
* `or`, `ror` and `ior`
* All the existing methods of `Set` will be ported to `FrozenSet`.

The following methods are not straight forward and needs some work.

* `difference`, `difference_update`, `intersection`,`intersection_update`, `union` and `update` (Implemented but needs improvements.)
* `isdisjoint`, `issubset` and `issuperset`
* `symmetric_difference` and `symmetric_difference_update`
* `format`

`socket` module
---------------------
In `socket` module I plan to implement 40 methods out of which 20 are simple and can be implemented directly using Java.net library.

The methods which can be implemented easily are:
* `getaddrinfo`, `gethostbyname`, `gethostbyname_ex`, `gethostname`, `gethostbyaddr`, `getnameinfo`, `getprotobyname`, `getservbyname`, `getservbyport`
* `ntohl`, `ntohs`, `htonl`, `htons`
* `inet_aton`, `inet_ntoa`, `inet_pton`, `inet_ntop`
* `getdefaulttimeout`, `setdefaulttimeout`, `sethostname`

The methods which needs hard work are:

* `socket`, `socketpair`, `create_connection`
* `connect`, `connect_ex`, `bind`, `close`
* `listen`, `accept`, `detach`, `dup`
* `recv`, `recvfrom`, `recvmsg`
* `send`, `sendall`, `sendto`
* `shutdown`,`settimeout`, `sendfile`.

Schedule
=======
Community  Bonding period: May 4 -May 30
-------------------------------------
* Get involved in the pybee community.
* Enhanced research on socket module and every methods planned to implement.
* Get friendly with other GSoC students.

Week 1: May 30 – June 2
------------------------------
* Enhance the `difference`, `difference_update`, `intersection` and `intersection_update` methods and implement them in `FrozenSet`.

Week 2: June 5 – June 9
-------------------
* Implement `isdisjoint`, `issubset` and `issuperset`.

Week 3: June 12 – June 16
---------------------
* Implement `symmetric_difference` and `symmetric_difference_update` and improve `union` and `update`.

Week 4: June 19 – June 23
---------------------
* Implement the 12 easy methods of the `Set` and `FrozenSet`.

Week 5: June 26 – June 30
------------------
* Implement `format` for `Set` and `FrozenSet`.

Week 6: July 3 – July 7
------------------
* Implement all the 20 easy methods of `socket` module.

Week 7: July 10 – July 14
-----------
* Implement `socket`, `create_connection` and `socketpair` of the `socket` module.

Week 8: July 17 – July 21
--------------
* Implement `connect`, `connect_ex`, `bind`, `close`.

Week 9: July 24 – July 28
-------------------------
* Implement `listen`, `accept`, `detach`, `dup`.

Week 10: July 31 – Aug 4
-----------------------
* Implement `send`, `sendall`, `sendto`.

Week 11: Aug 7 – Aug 11
------------------------
* Implement `recv`, `recvfrom`, `recvmsg`.

Week 12: Aug 14 – Aug 18
------------------------------
* Implement `shutdown`,`settimeout`, `sendfile`.

I assure to work 8 hours a day in weekdays. I will work on weekends if the project needs it.

My works
=======
2 of my pull requests got merged
* `swapcase()` for `Str` pybee/voc#412
* `split` for `Str` pybee/voc#433

1 pull request is open and I am working on it to improve it.
* `iterator` for Set, FrozenSet, and Tuple.

I also contributed to the batavia project
* `swapcase` for String pybee/batavia#465

**Comment by freakboy3742** [comment]
This is not bad as a first pass - but it needs a lot more detail. It reads like you've worked out what you want to do, and just split it up over 12 weeks - not that you've worked out how long things will take, and determined that it's 12 weeks of work. 

Some specific comments:

* The "not straight forward" set methods - why are they complex? Is it because they're not direct analogs to underlying Java operations? Or is there something difficult required to implement them?

* Socket is an interesting choice - it's *very* low level. Why is that a good target to implement? Are there advantages to implementing the socket API? Most end users won't be using socket directly - they'll be using httplib, email, or similar. Are those libraries dependent on socket? How much of socket is written in Python and can be re-used? How much is written in Python but *can't* be reused? And how much is a C layer that needs reimplementation?

* Assuming implementing socket is the best approach - is the implementation just a matter of wrapping Java APIs in Python? Or is there more manipulation required? Which Java API will you be using? 

* Are there any data types or structures defined as part of the socket module? Will you have to implement those as well?

**Comment by bitdumper1** [comment]
As per my research 
* The "not straight forward" methods accept any iterable object, so dealing with them is a litttle harder.
* `socket` is a good target to implement because httplib, email or similar are dependent on it. They need socket to work. `socket` written in python is only a wrapper above the  `_socket`, the C implementation providing additional facilities. Total of 6 method/functions can be used from the Python's implementation in python.
    * `makefile`, `dup`, `__repr__`, `family`, `type`, `getfqdn`, `create_connection`.
*  Most of the implementation needs wrapping Java APIs in python with a little manipulation. I will be using the Java's default net APIs.
* As of now I have came across only error and constants which need to be implemented. The socket initialization takes tuple.

**Comment by freakboy3742** [comment]
Unfortunately, this proposal wasn't accepted.
