### ISSUE TITLE
Typo in tutorial 0

### ISSUE THREAD

**Issue by pcsteppan** [pybee/voc#492]
[Tutorial 0](https://voc.readthedocs.io/en/latest/tutorials/tutorial-0.html) mentions the expected output upon running the VOC compiler over example.py is 

> Compiling example.py ...
Adding default main method...
Writing python/example/\_\_init\_\_.class ...

 While the actual output I received is only

> Compiling example.py ...
Writing .\python\example/\_\_init\_\_.class ...

**Comment by eliasdorneles** [comment]
Thanks for caring, but the tutorial is correct in this case, that was the expected output when compiling in Linux or OS X.

You're getting a different output because you're probably using Windows (maybe PowerShell?).

I'll close this ticket, feel free to comment or provide more details if my assumptions are incorrect.

**Comment by simsausaurabh** [comment]
@eliasdorneles sir
tutorial is correct in sense what has to be the actual output- `the generation of .class file` but as @pcsteppan mentioned `Adding default main method...` is not coming in terminal.
I am using - `Linux saurabh-HP-Notebook 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`.
and this line is not getting printed in terminal.
Thank you.
