### ISSUE TITLE
Precision of complex.__pow__ differs from results calculated by Python

### ISSUE THREAD

**Issue by soandrew** [pybee/voc#499]
The best way to see this problem is to comment out the [defined `substitutions` in the `BinaryComplexOperationTests` class test suite](https://github.com/pybee/voc/blob/master/tests/datatypes/test_complex.py#L54-L64) which is being used instead of the [`SAMPLE_DATA` from the `tests/utilis.py` file](https://github.com/pybee/voc/blob/master/tests/utils.py#L626-L632).

Then I ran:
```
python setup.py test -s tests.datatypes.test_complex.BinaryComplexOperationTests.test_power_complex
```
and encountered the following precision error
```
  >>> x = 1+2j
  >>> y = -5j
  >>> x ** y
- (-161.18751321137705+195.77962956590406j)
?                                       ^
+ (-161.18751321137705+195.77962956590403j)
?                                       ^
```
As shown, the code fails already existing tests. There was just a convenient choice of `substitutions` such that this precision error was not encountered.

As for a fix, I'm not too sure what can be done. Comparing the [algorithm used in `complex.__pow__`](https://github.com/pybee/voc/blob/master/python/common/org/python/types/Complex.java#L431-L503) to the [algorithm used by CPython](https://github.com/python/cpython/blob/master/Objects/complexobject.c#L116-L177), they appear to be essentially identical. (There was a typo which I submitted a fix for in PR #497).
So it appears the problem is just the slight difference in precision/representation of floats between Python and Java.

For completeness here are some other failing tests I discovered by adding `0+0j` and `1+0j` to the `complex` list in `SAMPLE_DATA`:
```
  >>> x = 1j
  >>> y = 1+0j
  >>> x ** y
- (6.123233995736766e-17+1j)
+ 1j

  >>> x = 3.14159265j
  >>> y = 1+0j
  >>> x ** y
- (1.9236706915236757e-16+3.14159265j)
+ 3.14159265j

  >>> x = 1+2j
  >>> y = 1+0j
  >>> x ** y
- (1.0000000000000002+2j)
+ (1+2j)

  >>> x = -5j
  >>> y = 1+0j
  >>> x ** y
- (3.061616997868383e-16-5j)
+ -5j

  >>> x = 3-4j
  >>> y = 1+0j
  >>> x ** y
- (3.0000000000000004-3.9999999999999996j)
+ (3-4j)
```

**Comment by cflee** [comment]
This thing on "precision error" seems to be entirely expected. Floating point calculations are generally not deterministic, so the substitution array exists _precisely_ to 'hide' the inaccuracies so that the test suite passes on the Travis CI environment.

The 'correct' way to compare floating point number is to see if they are 'close enough' within a certain epsilon (see the [Floating-Point Guide](http://floating-point-gui.de/errors/comparison/)). Unfortunately, we don't have a trivial way of doing that right now since we are just checking equality on the outputs.

If adding those two complex samples to `SAMPLE_DATA` is necessary to catch some edge cases (apart from these "precision" errors), then the differences (based on how the tests are failing on Travis) should be added to the `substitutions` array.

**Comment by soandrew** [comment]
@cflee Ah I see. I think I completely misunderstood what the `substitutions` array was doing then. So each time the outputs aren't exactly equal we can just hard code the expected outputs into that array?

And yes, having those two complex samples would have caught the typo found so I believe that it is a necessary test.
