### ISSUE TITLE
bytes.__iadd__ has different behaviour in Python 3.6 and <3.6

### ISSUE THREAD

**Issue by uranusjr** [pybee/voc#595]
Up until Python 3.5.x there is a bug in `bytes.__iadd__` that raises TypeError with incorrect error message. [This is fixed in 3.6](https://github.com/python/cpython/pull/709), but causes tests to fail in #593. How do I resolve this?

**Comment by eliasdorneles** [comment]
Hi @uranusjr -- sorry for the delay!
I think we don't need to replicate CPython bugs in VOC -- considering we're looking at the future here and VOC is in its early days. =)

So in the cases where the implementations are buggy for some lower CPython versions, we can ignore the test in the buggy versions.
Preferably this decision would be documented in the code, so that we can change it in the future if the bugfix is backported to 3.5.x.

**Comment by uranusjr** [comment]
Fixed in #607?
