### ISSUE TITLE
test_modulo_int for BinaryStrOperationTests passes although edge cases are not taken care of

### ISSUE THREAD

**Issue by janmax** [pybee/voc#638]
Hi,

I just stumbled over this project and decided to take some first steps towards contributing to it - first time contribution to a project. So go easy on me if I got something completely wrong here. I wanted to implement some method for the `org.python.types.Str` class and got a little lost:

While executing the following code in Python 3.4.4 I can see various types of errors for a `str % int` kind of expression:
```python
f_options = [
    # Works
    "'%s'       % 314", # works: 314
    "'%% %d %%' % 314", # works: % 314 %
    "'%s % % '  % 314", # works: 314 %
    # Fails
    "'%s %s'    % 314", # fails: TypeError not enough arguments for format string
    "'empty'    % 314", # fails: TypeError not all arguments converted during string formatting
    "'%d % inc' % 314", # fails: TypeError not enough arguments for format string
    "'%s %% %'  % 314", # fails: ValueError incomplete format
    "'Hello %P' % 314", # fails: ValueError unsupported format character 'P' (0x50) at index 7
    "'%(map)s'  % 314", # fails: TypeError format requires a mapping
]

for formatted in f_options:
    try:
        print(formatted, 'WORKS', '->', eval(formatted))
    except Exception as e:
        print(formatted, 'FAILS', type(e).__name__, e)

```

Exact result:
```
'%s'       % 314 WORKS -> 314
'%% %d %%' % 314 WORKS -> % 314 %
'%s % % '  % 314 WORKS -> 314 %
'%s %s'    % 314 FAILS TypeError not enough arguments for format string
'empty'    % 314 FAILS TypeError not all arguments converted during string formatting
'%d % inc' % 314 FAILS TypeError not enough arguments for format string
'%s %% %'  % 314 FAILS ValueError incomplete format
'Hello %P' % 314 FAILS ValueError unsupported format character 'P' (0x50) at index 7
'%(map)s'  % 314 FAILS TypeError format requires a mapping
```

The solution to test `test_modulo_int` in #616 does not cover much besides the default case (More precisely only the 0., 3. and 4. case are handled in compliance with Python3.4's handling). 

It seems to me that for most testcases where `__mod__` on `str` is called with another none iterable type the same problem occurs. Therefore, I have three questions before I decide if I feel comfortable implementing anything in full (or someone argues that's too much for a first-time-contribution):

1. Where is the testcase that would actually check the cases in the code above are covered? Or where would I have to put one? 

2. Will this in the end, require to reimplement the entire mini-language used for printf-style formatting including the additional Python features like maps?

3. Or, would merely passing everything to the java formatter, catching the Exceptions and re-throw a corresponding Python error be sufficient? (Sounds like an ugly workaround imho.)

Thanks for any help on this.

**Comment by freakboy3742** [comment]
You're completely correct - the test case in #616 does little more than fix a very simple case. The mod operator on string isn't a simple problem, because you have to implement the full `%` parsing and substitution engine implemented by Python (to say nothing of the `format()` method). 

Batavia (VOC's sibling project for working in Javascript) has an implementation that is much more complete, thanks to the efforts of @jstoebel; that implementation might be a good place to start if you're looking to contribute.

Just using the Java formatter isn't an option (at least, not a *complete* option) because Java's formatter and Python's are slightly different. You *might* be able to use Java's formatter as a starting point, but the end goal is 100% compatibility with CPython, so you'll have to find and catch all the edge cases. You'll probably find it's easier to just re-implement.

As for whether this is "appropriate" for a first time contributor - it's not the easiest ticket in the world, but it's well defined, and your analysis indicates that you're switched on enough to know what the key problems will be. It will definitely be a challenge, but it should be completely achievable for a first-time contributor if you're willing to persevere a bit.

**Comment by janmax** [comment]
Thanks for your reply! I just started working on it (I'll link this issue in #36). As my main resources I already used:

* [The Python specification for printf formatting](https://docs.python.org/3/library/stdtypes.html#old-string-formatting)
* [The Java 8 specification on java.util.Formatter](https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html)
* and maybe [the actual CPython implementation](https://svn.python.org/projects/python/trunk/Objects/stringobject.c)

Thanks for pointing me to [the JS implementation](https://github.com/pybee/batavia/blob/961f30c5842577931a597846a4b54bfd644b8497/batavia/types/StrUtils.js) of @jstoebel as well. That gives a good estimator of who much work this will be. The way Java handles format strings is actually pretty similar to the old-style Python way, so maybe there is a chance of delegating so parts to java.util.formatter after doing the checks. I'll see.

And, is there a place where I can put my test cases?

**Comment by uranusjr** [comment]
@janmax The `str.__mod__` implementation of Python 3 is `PyUnicode_Format` in `unicodeobject.c`. The file you referenced is from the old Python 2 tree (which is now called `bytesobject.c`).

https://github.com/python/cpython/blob/v3.6.2/Objects/unicodeobject.c#L14861
