### ISSUE TITLE
Error: can't find class file while running the class file on java

### ISSUE THREAD

**Issue by Vab-jain** [pybee/voc#722]
Following the tutorial, after running VOC over example.py, the next command i.e.
`$ java -classpath ../voc/dist/python-java-support.jar:. python.example`
gives the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at python.sys.<clinit>(sys.java:76)
	at python.example.main(example.py)
Caused by: RuntimeError: Unknown platform vendor 'Azul Systems, Inc.'
	at python.platform.<clinit>(platform.java:29)
	... 2 more
```

When used with `-v`, it gives:
`Error: Could not find or load main class ...voc.dist.python-java-support.jar:.`

But the file "python-java-support.jar" exist at the given location.

**Comment by eliasdorneles** [comment]
Which operating system are you running?

**Comment by Vab-jain** [comment]
Ubuntu 16.04

**Comment by eliasdorneles** [comment]
Right, I see now from the stacktrace that you seem to be using Azul's Zing JVM.
That isn't recognized as a platform by [the current code](https://github.com/pybee/voc/blob/master/python/common/python/platform.java#L24-L30), hmm, we need to fix that.
I'm using OpenJDK, and `java.vendor` is printing `Oracle Corporation` (which is a bit unexpected, since this isn't Oracle's official JDK).

Anyway, I think a decent fix would be to another if clause there for the Azul case, and handle it the same as the case for "Oracle Corporation".

**Comment by uranusjr** [comment]
@eliasdorneles OpenJDK *is* developed by Oracle, after all…
